version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: app
    ports:
      - "4444:4444"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongo:27017/maBase

volumes:
  mongo_data:
