version: "3"
services:
  web:
    build: .
    ports:
      - "4444:4444"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
